export const ADD_TO_DO = 'ADD_TO_DO';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_MAIN_LIST_BEGIN = 'FETCH_MAIN_LIST_BEGIN';
export const FETCH_MAIN_LIST_SUCCESS = 'FETCH_MAIN_LIST_SUCCESS';
export const FETCH_MAIN_LIST_FAILURE = 'FETCH_MAIN_LIST_FAILURE';
